ⓒ JMC 2017

**source**: http://nbviewer.jupyter.org/github/rougier/numpy-100/blob/master/100%20Numpy%20exercises.ipynb

---

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercices for those who teach.

If you find an error or think you've a better way to solve some of them, feel free to open an issue at https://github.com/rougier/numpy-100

**1. Import the numpy package under the name `np` (★☆☆)**

In [1]:
import numpy as np

**2. Print the numpy version and the configuration (★☆☆)** 

In [2]:
print(np.__version__)
np.show_config()

1.13.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
    language = c
    define_macros = [('HAVE_CBLAS', None), ('ATLAS_INFO', '"\\"None\\""')]
    libraries = ['numpy-atlas']
    library_dirs = ['C:\\projects\\numpy-wheels\\windows-wheel-builder\\atlas-builds\\atlas-3.10.1-sse2-32\\lib']
blas_opt_info:
    language = c
    define_macros = [('HAVE_CBLAS', None), ('ATLAS_INFO', '"\\"None\\""')]
    libraries = ['numpy-atlas']
    library_dirs = ['C:\\projects\\numpy-wheels\\windows-wheel-builder\\atlas-builds\\atlas-3.10.1-sse2-32\\lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
    language = f77
    libraries = ['numpy-atlas', 'numpy-atlas']
    library_dirs = ['C:\\projects\\numpy-wheels\\windows-wheel-builder\\atlas-builds\\atlas-3.10.1-sse2-32\\lib']
    define_macros = [('ATLAS_INFO', '"\\"None\\""')]
lapack_opt_info:
    language = f77
    libraries = ['

**3. Create a null vector of size 10 (★☆☆)**

In [3]:
Z = np.zeros(10)
print(Z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


**4. How to find the memory size of any array (★☆☆)**

In [7]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))
print(Z)

800 bytes
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


**5. How to get the documentation of the numpy add function from the command line? (★☆☆)**

In [5]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


**6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)**

In [8]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


**7. Create a vector with values ranging from 10 to 49 (★☆☆)**

In [9]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**8. Reverse a vector (first element becomes last) (★☆☆)**

In [10]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


**9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)**

In [12]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**10. Find indices of non-zero elements form [1,2,0,0,4,0] (★☆☆)**

In [13]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int32),)


**11. Create a 3x3 identity matrix (★☆☆)**

In [14]:
Z = np.eye(3)
print(Z)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


**12. Create a 3x3 array with random values (★☆☆)**

In [15]:
Z = np.random.random((3,3,3))
print(Z)

[[[ 0.97689478  0.08810239  0.64122183]
  [ 0.54261905  0.91311291  0.78261513]
  [ 0.42399889  0.81421635  0.6864109 ]]

 [[ 0.01435876  0.17334954  0.08447112]
  [ 0.75185665  0.76479753  0.911235  ]
  [ 0.03388975  0.99221651  0.85678438]]

 [[ 0.13525379  0.22978422  0.38518997]
  [ 0.80515225  0.36163563  0.23546895]
  [ 0.69590847  0.89601415  0.90873424]]]


**13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)**

In [16]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.00419229784035 0.992240151816


**14. Create a random vector of size 30 and find the mean value (★☆☆)**

In [17]:
Z = np.random.random(30)
Zmean = Z.mean()
print(Zmean)

0.544290933821


**15. Create a 2d array with 1 on the border and 0 insde (★☆☆)**

+ `Z[1:-1, 1:-1]`
    + row : row[1]~raw[-1]

In [19]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
