ⓒ JMC 2017

**source**: http://nbviewer.jupyter.org/github/rougier/numpy-100/blob/master/100%20Numpy%20exercises.ipynb

---

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercices for those who teach.

If you find an error or think you've a better way to solve some of them, feel free to open an issue at https://github.com/rougier/numpy-100

**1. Import the numpy package under the name `np` (★☆☆)**

In [1]:
import numpy as np

**2. Print the numpy version and the configuration (★☆☆)** 

In [2]:
print(np.__version__)
np.show_config()

1.13.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
    language = c
    define_macros = [('HAVE_CBLAS', None), ('ATLAS_INFO', '"\\"None\\""')]
    libraries = ['numpy-atlas']
    library_dirs = ['C:\\projects\\numpy-wheels\\windows-wheel-builder\\atlas-builds\\atlas-3.10.1-sse2-32\\lib']
blas_opt_info:
    language = c
    define_macros = [('HAVE_CBLAS', None), ('ATLAS_INFO', '"\\"None\\""')]
    libraries = ['numpy-atlas']
    library_dirs = ['C:\\projects\\numpy-wheels\\windows-wheel-builder\\atlas-builds\\atlas-3.10.1-sse2-32\\lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
    language = f77
    libraries = ['numpy-atlas', 'numpy-atlas']
    library_dirs = ['C:\\projects\\numpy-wheels\\windows-wheel-builder\\atlas-builds\\atlas-3.10.1-sse2-32\\lib']
    define_macros = [('ATLAS_INFO', '"\\"None\\""')]
lapack_opt_info:
    language = f77
    libraries = ['

**3. Create a null vector of size 10 (★☆☆)**

In [3]:
Z = np.zeros(10)
print(Z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


**4. How to find the memory size of any array (★☆☆)**

In [4]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))
print(Z)

800 bytes
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


**5. How to get the documentation of the numpy add function from the command line? (★☆☆)**

In [5]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


**6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)**

In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


**7. Create a vector with values ranging from 10 to 49 (★☆☆)**

In [7]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**8. Reverse a vector (first element becomes last) (★☆☆)**

In [8]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


**9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)**

In [9]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**10. Find indices of non-zero elements form [1,2,0,0,4,0] (★☆☆)**

In [10]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int32),)


**11. Create a 3x3 identity matrix (★☆☆)**

In [11]:
Z = np.eye(3)
print(Z)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


**12. Create a 3x3 array with random values (★☆☆)**

In [12]:
Z = np.random.random((3,3,3))
print(Z)

[[[ 0.17096631  0.81658357  0.96749409]
  [ 0.14694977  0.04228669  0.38040465]
  [ 0.61855093  0.32830144  0.21041532]]

 [[ 0.14982002  0.82741846  0.47083697]
  [ 0.71495508  0.08448033  0.38500345]
  [ 0.15479338  0.28167445  0.86533551]]

 [[ 0.49988037  0.78184972  0.02021851]
  [ 0.57865942  0.68842933  0.67560018]
  [ 0.37878888  0.98603712  0.62932711]]]


**13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)**

In [13]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0129707611927 0.98328002709


**14. Create a random vector of size 30 and find the mean value (★☆☆)**

In [14]:
Z = np.random.random(30)
Zmean = Z.mean()
print(Zmean)

0.496578393054


**15. Create a 2d array with 1 on the border and 0 insde (★☆☆)**

+ `Z[1:-1, 1:-1]`
    + row : row[1]~raw[-1]

In [15]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


**16. How to add a border (filled with 0's) around an existing arraY? (★☆☆)**

In [16]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


**17. What is the result of the following expression? (★☆☆)**

@@@question

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


**18. Create a 5x5 matrix with values 1,2,3,4 just below the diagnol (★☆☆)**

In [25]:
Z = np.diag(1+np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [22]:
1+np.arange(4)

array([1, 2, 3, 4])

In [23]:
np.arange(4)

array([0, 1, 2, 3])

**19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)**

@@@question

In [27]:
Z = np.zeros((8,8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?  (★☆☆)**

@@@알듯말듯

In [34]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


**21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)**

`np.tile(array, (4,4))`

+ 첫번째 argument인 `array`를 block matrix로 생각하여 row에 4번, column에 4번 반복한다.

In [37]:
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**22. Normalize a 5x5 random matrix (★☆☆)**

In [43]:
Z = np.random.random((5,5))
Zmax, Zmin, Zmean = Z.max(), Z.min(), Z.mean()
Z = (Z -Zmean)/(Zmax-Zmin)
print(Z)

[[  3.70371893e-01   8.03775563e-02   1.34046483e-04  -5.00905107e-01
    3.13673269e-01]
 [ -2.20849682e-01   1.47064536e-01  -3.50988010e-01  -9.64042107e-02
   -2.65285371e-01]
 [ -5.20519283e-01   4.04198551e-01   3.30360578e-01   3.45414445e-01
   -2.31425047e-01]
 [  2.47864347e-01   2.05016398e-01  -5.67872161e-01  -2.46939707e-02
    1.64711746e-01]
 [ -5.19032188e-02  -5.95801449e-01   1.89771875e-01   2.65779062e-01
    3.61909207e-01]]


**23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)**

@@@question

In [45]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

**24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)**